name: pegasus-env3
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - nltk
  - tqdm
  - regex
  - pytz
  - jinja2
  - filelock
  - fsspec
  - sentencepiece
  - ca-certificates
  - openssl
  - pip:
      - transformers==4.51.3
      - torch==2.7.0
      - tiktoken==0.9.0
      - huggingface-hub==0.30.2
      - tokenizers==0.21.1
      - safetensors==0.5.3
